# Generated by Django 2.0.4 on 2018-04-26 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattch',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='postattch',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Attachment'),
        ),
        migrations.DeleteModel(
            name='PostAttch',
        ),
    ]
