# Generated by Django 2.0.4 on 2018-04-24 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180424_1733'),
        ('polls', '0003_question_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='image',
            new_name='url',
        ),
        migrations.AddField(
            model_name='question',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Attachment'),
        ),
        migrations.AddField(
            model_name='question',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
