# Generated by Django 2.0.4 on 2018-04-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_question_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='creator',
            new_name='author',
        ),
    ]
