# Generated by Django 2.0.4 on 2018-04-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180426_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='attachment',
        ),
    ]
