# Generated by Django 2.0.4 on 2018-04-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180426_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='city',
        ),
        migrations.RemoveField(
            model_name='information',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='information',
            name='region',
        ),
        migrations.AddField(
            model_name='information',
            name='useragent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
