# Generated by Django 2.0.4 on 2018-04-26 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_attachment'),
        ('polls', '0009_auto_20180426_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='image',
        ),
        migrations.AddField(
            model_name='choice',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Attachment'),
        ),
        migrations.AddField(
            model_name='choice',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
