# Generated by Django 2.0.4 on 2018-04-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20180427_1300'),
        ('polls', '0014_question_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='posts.Tag'),
        ),
    ]
